databases:
- name: weather-db
  databaseName: weather_db_teek
  user: weather_db_teek_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"

services:
  - type: web
    name: Toyo_University_YM_iniad_7GxwNLu9C4g7wriM
    env: python
    plan: Starter
    branch: master
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.2
      - key: DATABASE_URL
        fromDatabase:
          name: weather-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.production
      - key: WEB_CONCURRENCY
        value: 4