services:
  - type: web
    name: Toyo_University_YM_iniad_7GxwNLu9C4g7wriM
    env: python
    plan: free
    branch: azure
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.2
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.production
      - key: WEB_CONCURRENCY
        value: 4
